class VantaDBRM:
    def __init__(self, db_path: str, collection: str = "dspy_passages") -> None: ...
    def forward(self, query_embedding: list[float], k: int = 10) -> list[dict]: ...
    def add_passage(self, passage: str, embedding: list[float], metadata: dict | None = None) -> str: ...

__version__: str
