"""Type stubs for the vantadb_py package."""
from __future__ import annotations

from typing import Any

class VantaVector:
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> float: ...
    def __repr__(self) -> str: ...

class VantaSearchHit:
    namespace: str
    key: str
    payload: str
    metadata: dict
    vector: VantaVector | None
    score: float
    id: int
    created_at_ms: int
    updated_at_ms: int
    version: int
    node_id: int
    expires_at_ms: int | None
    def __repr__(self) -> str: ...

class VantaDB:
    def __init__(
        self,
        db_path: str,
        memory_limit_bytes: int | None = None,
        read_only: bool = False,
        backend: str | None = None,
    ) -> None: ...
    def insert(
        self, id: int, content: str, vector: Any, fields: dict | None = None
    ) -> None: ...
    def put(
        self,
        namespace: str,
        key: str,
        payload: str,
        metadata: dict | None = None,
        vector: Any | None = None,
        ttl_ms: int | None = None,
    ) -> dict: ...
    def put_batch(
        self, entries: list[tuple[str, str, str, dict | None, Any | None, int | None]]
    ) -> list[dict]: ...
    def put_batch_raw(
        self,
        vectors: Any,
        keys: list[str],
        payloads: list[str] | None = None,
        metadatas: list[dict | None] | None = None,
        namespaces: list[str] | None = None,
        ttls: list[int | None] | None = None,
    ) -> list[dict]: ...
    def get_memory(self, namespace: str, key: str) -> dict | None: ...
    def delete_memory(self, namespace: str, key: str) -> bool: ...
    def search_memory(
        self,
        namespace: str,
        query_vector: Any,
        filters: dict | None = None,
        text_query: str | None = None,
        top_k: int = 10,
        distance_metric: str | None = None,
        explain: bool = False,
    ) -> list[VantaSearchHit]: ...
    def list_memory(
        self,
        namespace: str,
        filters: dict | None = None,
        limit: int = 100,
        cursor: int | None = None,
    ) -> dict: ...
    def rebuild_index(self) -> dict: ...
    def export_namespace(self, path: str, namespace: str) -> dict: ...
    def export_all(self, path: str) -> dict: ...
    def import_file(self, path: str) -> dict: ...
    def audit_text_index(
        self, namespace: str | None = None, deep: bool = False
    ) -> dict: ...
    def repair_text_index(self) -> dict: ...
    def operational_metrics(self) -> dict: ...
    def get(self, id: int) -> dict | None: ...
    def delete(self, id: int, reason: str = "manual deletion") -> None: ...
    def search(
        self, vector: Any, top_k: int = 10
    ) -> list[tuple[int, float]]: ...
    def search_batch(
        self, vectors: list[Any], top_k: int = 10
    ) -> list[list[tuple[int, float]]]: ...
    def query(self, iql_query: str) -> str: ...
    def flush(self) -> None: ...
    def compact_wal(self) -> None: ...
    def purge_expired(self) -> int: ...
    def capabilities(self) -> dict: ...
    def hardware_profile(self) -> dict: ...
    def add_edge(
        self,
        source_id: int,
        target_id: int,
        label: str,
        weight: float | None = None,
    ) -> None: ...
    def close(self) -> None: ...
    def graph_bfs(
        self, roots: list[int], max_depth: int = 999999
    ) -> list[int]: ...
    def graph_dfs(
        self, roots: list[int], max_depth: int = 999999
    ) -> list[int]: ...
    def graph_topological_sort(self, roots: list[int]) -> list[int]: ...
    def graph_is_dag(self, roots: list[int]) -> bool: ...
    def compact_layout(self) -> int: ...
    def list_namespaces(self) -> list[str]: ...
    def generate_snippet(
        self,
        payload: str,
        text_query: str,
        with_highlighting: bool = False,
    ) -> str | None: ...
    def explain_memory_search(
        self,
        namespace: str,
        query_vector: list[float],
        filters: dict | None = None,
        text_query: str | None = None,
        top_k: int = 10,
        distance_metric: str | None = None,
    ) -> dict: ...

class AsyncVantaDB:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def __aenter__(self) -> AsyncVantaDB: ...
    async def __aexit__(self, *exc: Any) -> None: ...
    async def search_memory(
        self,
        namespace: str,
        query_vector: list[float],
        *,
        filters: dict | None = None,
        text_query: str | None = None,
        top_k: int = 10,
        distance_metric: str | None = None,
        explain: bool = False,
    ) -> list[VantaSearchHit]: ...
    async def get_memory(self, namespace: str, key: str) -> dict | None: ...
    async def list_memory(
        self,
        namespace: str,
        *,
        filters: dict | None = None,
        limit: int = 100,
        cursor: int | None = None,
    ) -> dict: ...
    async def put(
        self,
        namespace: str,
        key: str,
        payload: str,
        *,
        metadata: dict | None = None,
        vector: list[float] | None = None,
        ttl_ms: int | None = None,
    ) -> dict: ...
    async def delete_memory(self, namespace: str, key: str) -> bool: ...
    async def compact_wal(self) -> None: ...
    async def purge_expired(self) -> int: ...
    async def flush(self) -> None: ...
    async def close(self) -> None: ...
    async def insert(
        self, id: int, content: str, vector: Any, fields: dict | None = None
    ) -> None: ...
    async def put_batch(
        self, entries: list[tuple[str, str, str, dict | None, Any | None, int | None]]
    ) -> list[dict]: ...
    async def rebuild_index(self) -> dict: ...
    async def export_namespace(self, path: str, namespace: str) -> dict: ...
    async def export_all(self, path: str) -> dict: ...
    async def import_file(self, path: str) -> dict: ...
    async def audit_text_index(
        self, namespace: str | None = None, deep: bool = False
    ) -> dict: ...
    async def repair_text_index(self) -> dict: ...
    async def operational_metrics(self) -> dict: ...
    async def get(self, id: int) -> dict | None: ...
    async def delete(self, id: int, reason: str = "manual deletion") -> None: ...
    async def search(
        self, vector: Any, top_k: int = 10
    ) -> list[tuple[int, float]]: ...
    async def search_batch(
        self, vectors: list[Any], top_k: int = 10
    ) -> list[list[tuple[int, float]]]: ...
    async def query(self, iql_query: str) -> str: ...
    async def capabilities(self) -> dict: ...
    async def hardware_profile(self) -> dict: ...
    async def add_edge(
        self,
        source_id: int,
        target_id: int,
        label: str,
        weight: float | None = None,
    ) -> None: ...
    async def graph_bfs(
        self, roots: list[int], max_depth: int = 999999
    ) -> list[int]: ...
    async def graph_dfs(
        self, roots: list[int], max_depth: int = 999999
    ) -> list[int]: ...
    async def graph_topological_sort(self, roots: list[int]) -> list[int]: ...
    async def graph_is_dag(self, roots: list[int]) -> bool: ...
    async def compact_layout(self) -> int: ...
    async def list_namespaces(self) -> list[str]: ...
    async def generate_snippet(
        self,
        payload: str,
        text_query: str,
        with_highlighting: bool = False,
    ) -> str | None: ...
    async def explain_memory_search(
        self,
        namespace: str,
        query_vector: list[float],
        *,
        filters: dict | None = None,
        text_query: str | None = None,
        top_k: int = 10,
        distance_metric: str | None = None,
    ) -> dict: ...
    def __repr__(self) -> str: ...

def connect(path: str, memory_limit: int | None = None) -> VantaDB: ...
def __version__() -> str: ...
