"""Type stubs for the Rust-native ``vantadb_py`` module."""

from __future__ import annotations

from typing import Any


class VantaDB:
    def __init__(
        self,
        db_path: str,
        memory_limit_bytes: int | None = None,
        read_only: bool = False,
        backend: str | None = None,
    ) -> None: ...
    def insert(
        self, id: int, content: str, vector: Any, fields: dict | None = None
    ) -> None: ...
    def put(
        self,
        namespace: str,
        key: str,
        payload: str,
        metadata: dict | None = None,
        vector: Any | None = None,
        ttl_ms: int | None = None,
    ) -> dict: ...
    def put_batch(
        self, entries: list[tuple[str, str, str, dict | None, Any | None, int | None]]
    ) -> list[dict]: ...
    def get_memory(self, namespace: str, key: str) -> dict | None: ...
    def delete_memory(self, namespace: str, key: str) -> bool: ...
    def search_memory(
        self,
        namespace: str,
        query_vector: Any,
        filters: dict | None = None,
        text_query: str | None = None,
        top_k: int = 10,
        distance_metric: str | None = None,
        explain: bool = False,
    ) -> list[dict]: ...
    def list_memory(
        self,
        namespace: str,
        filters: dict | None = None,
        limit: int = 100,
        cursor: int | None = None,
    ) -> dict: ...
    def rebuild_index(self) -> dict: ...
    def export_namespace(self, path: str, namespace: str) -> dict: ...
    def export_all(self, path: str) -> dict: ...
    def import_file(self, path: str) -> dict: ...
    def audit_text_index(
        self, namespace: str | None = None, deep: bool = False
    ) -> dict: ...
    def repair_text_index(self) -> dict: ...
    def operational_metrics(self) -> dict: ...
    def get(self, id: int) -> dict | None: ...
    def delete(self, id: int, reason: str = "manual deletion") -> None: ...
    def search(
        self, vector: Any, top_k: int = 10
    ) -> list[tuple[int, float]]: ...
    def search_batch(
        self, vectors: list[Any], top_k: int = 10
    ) -> list[list[tuple[int, float]]]: ...
    def query(self, iql_query: str) -> str: ...
    def flush(self) -> None: ...
    def compact_wal(self) -> None: ...
    def purge_expired(self) -> int: ...
    def capabilities(self) -> dict: ...
    def hardware_profile(self) -> dict: ...
    def add_edge(
        self,
        source_id: int,
        target_id: int,
        label: str,
        weight: float | None = None,
    ) -> None: ...
    def close(self) -> None: ...
    def graph_bfs(
        self, roots: list[int], max_depth: int = 999999
    ) -> list[int]: ...
    def graph_dfs(
        self, roots: list[int], max_depth: int = 999999
    ) -> list[int]: ...
    def graph_topological_sort(self, roots: list[int]) -> list[int]: ...
    def graph_is_dag(self, roots: list[int]) -> bool: ...


def __version__() -> str: ...
