config:
  MD013: false
  MD033:
    allowed_elements:
      - div
      - h1
      - p
      - b
      - br
  MD041: false

globs:
  - "**/*.md"
  - "**/*.MD"

ignores:
  - ".github/ISSUE_TEMPLATE/*.yml"
