class LettaStore:
    def __init__(self, path: str, _collection_name: str = "letta_memories") -> None: ...
    def store_memory(self, user_id: str, agent_id: str, content: str, embedding: list[float]) -> str: ...
    def retrieve_memory(self, user_id: str, agent_id: str, query_embedding: list[float], top_k: int = 5) -> list[dict]: ...
    def list_memories(self, user_id: str, agent_id: str) -> list[dict]: ...
    def delete_memory(self, memory_id: str) -> None: ...

__version__: str
