from haystack.dataclasses import Document

class VantaDBDocumentStore:
    def __init__(self, db_path: str, namespace: str = "haystack_docs") -> None: ...
    def write_documents(self, documents: list[dict | Document]) -> list[str]: ...
    def filter_documents(self, filters: dict | None = None, top_k: int = 100) -> list[Document]: ...
    def delete_documents(self, document_ids: list[str]) -> None: ...
    def count_documents(self) -> int: ...

__version__: str
