class VantaDBOpenAI:
    def __init__(self, db_path: str, api_key: str, model: str = "text-embedding-3-small", namespace: str = "openai_store") -> None: ...
    def embed(self, texts: list[str]) -> list[list[float]]: ...
    def search(self, query_embedding: list[float], top_k: int) -> list[dict]: ...
    def store(self, text: str, embedding: list[float], metadata: dict | None = None) -> str: ...

__version__: str
