class CrewAIMemory:
    def __init__(self, db_path: str, namespace: str = "crewai_memories") -> None: ...
    def save(self, context: str, metadata: dict, embedding: list[float]) -> str: ...
    def search(self, query_embedding: list[float], top_k: int = 5, threshold: float = 0.0) -> list[dict]: ...
    def clear(self) -> None: ...

__version__: str
