class VantaDBOllama:
    def __init__(self, db_path: str, base_url: str = "http://localhost:11434", model: str = "nomic-embed-text", namespace: str = "ollama_store") -> None: ...
    def embed(self, texts: list[str]) -> list[list[float]]: ...
    def search(self, query_embedding: list[float], top_k: int) -> list[dict]: ...
    def store(self, text: str, embedding: list[float], metadata: dict | None = None) -> str: ...

__version__: str
