class VantaDBVectorStore:
    def __init__(self, db_path: str, collection: str = "langchain_store") -> None: ...
    def add_texts(self, texts: list[str], embeddings: list[list[float]], metadatas: list[dict | None] | None = None, ids: list[str | None] | None = None) -> list[str]: ...
    def similarity_search_by_vector(self, embedding: list[float], k: int = 10) -> list[dict]: ...
    def delete(self, ids: list[str]) -> None: ...

__version__: str
