class VantaDBOpenAI:
    def __init__(
        self,
        db_path: str,
        api_key: str,
        model: str = "text-embedding-3-small",
        namespace: str = "openai_store",
        timeout: float | None = None,
    ) -> None: ...
    def embed(self, texts: list[str]) -> list[list[float]]: ...
    def embed_batch(self, texts: list[str], batch_size: int = 100) -> list[list[float]]: ...
    def search(
        self,
        namespace: str,
        query_embedding: list[float],
        text_query: str | None = None,
        filters: dict[str, str] | None = None,
        distance_metric: str | None = None,
        top_k: int = 10,
    ) -> list[dict]: ...
    def store(
        self,
        text: str,
        embedding: list[float],
        metadata: dict | None = None,
    ) -> str: ...
    def delete(self, key: str, namespace: str | None = None) -> bool: ...
    def get(self, namespace: str, key: str) -> dict | None: ...
    def list(self, namespace: str, limit: int = 100, cursor: int | None = None) -> dict: ...
    def list_namespaces(self) -> list[str]: ...

__version__: str


# ─── MOD-20 parity error hierarchy (ERR-PY-01) ─────────────────────────────
# Raised by every storage method; metadata attrs per docs/api/ERROR_HANDLING.md
# §5.1. Distinct class objects from vantadb_py's — cross-module catching is not
# supported (share via vantadb-python re-export if a 3rd consumer appears).
# exc.to_dict() is not a method (create_exception limitation): build a plain
# dict from code/retriable/hint/message, see docs/api/PYTHON_SDK.md.

class VantaError(RuntimeError):
    code: str
    retriable: bool
    hint: str | None
    ...

class NotFoundError(VantaError): ...
class ValidationError(VantaError): ...
class CorruptError(VantaError): ...
class StorageError(VantaError): ...
class ConflictError(VantaError): ...
class UnsupportedError(VantaError): ...
class ResourceLimitError(VantaError): ...
class BusyError(VantaError): ...
class NoVectorError(VantaError): ...
class TimeoutError(VantaError): ...