class VantaDBVectorStore:
    def __init__(self, db_path: str, collection: str = "llamaindex_store") -> None: ...
    def add(self, texts: list[str], embeddings: list[list[float]], metadatas: list[dict | None] | None = None, ids: list[str | None] | None = None) -> list[str]: ...
    def query(self, embedding: list[float], top_k: int = 10) -> list[dict]: ...
    def delete(self, ids: list[str]) -> None: ...

__version__: str
