class VantaDBStore:
    def __init__(self, path: str, collection_name: str = "memories") -> None: ...
    def create_col(self, name: str, vector_size: int, distance: str) -> None: ...
    def insert(self, vectors: list[list[float]], payloads: list[str | None] | None = None, ids: list[str] | None = None) -> list[str]: ...
    def search(self, query: str, vectors: list[list[float]], top_k: int = 5, filters: dict | None = None) -> list[dict]: ...
    def delete(self, vector_id: str) -> None: ...
    def update(self, vector_id: str, vector: list[list[float]] | None = None, payload: str | None = None) -> None: ...
    def get(self, vector_id: str) -> dict | None: ...
    def list_cols(self) -> list[str]: ...
    def delete_col(self) -> None: ...
    def col_info(self) -> dict: ...
    def list(self, filters: dict | None = None, top_k: int | None = None) -> list[dict]: ...
    def reset(self) -> None: ...

__version__: str
