// ponytail: bench helpers unwrap with documented invariants; documented per-call.
#![allow(clippy::expect_used, clippy::unwrap_used)]

//! Shared benchmarking utilities for VantaDB criterion benches.
//!
//! Provides a deterministic measurement profile (so nightly runs are
//! comparable run-to-run) and a deterministic synthetic dataset
//! generator/loader. The dataset file (`benches/data/synthetic_dataset.bin`)
//! is committed so benches can rely on a stable, reproducible input without
//! regenerating randomness at runtime.

// Shared bench utility compiled into each bench crate separately, so a helper
// used by only some benches would otherwise warn as dead_code under -D warnings.
#![allow(dead_code)]

use criterion::measurement::WallTime;
use criterion::BenchmarkGroup;
use std::path::Path;
use std::time::Duration;

/// Fixed seed for the deterministic synthetic dataset / generator.
pub const DATASET_SEED: u64 = 0x9E37_79B9_7F4A_7C15;
/// Dimensionality of the committed baseline dataset.
pub const DATASET_DIM: usize = 256;
/// Number of vectors in the committed baseline dataset.
pub const DATASET_COUNT: usize = 2_000;
/// Path to the committed deterministic dataset (relative to workspace root).
pub const DATASET_PATH: &str = "benches/data/synthetic_dataset.bin";

/// Fixed measurement profile shared by all regression-tracked benches.
///
/// Fixes warm-up / measurement time and statistical thresholds so criterion
/// estimates are stable run-to-run. Per-bench `sample_size` is intentionally
/// left to each bench (heavy benches like `high_density` tune it deliberately).
pub fn apply_fixed_profile(g: &mut BenchmarkGroup<'_, WallTime>) {
    g.warm_up_time(Duration::from_secs(3));
    g.measurement_time(Duration::from_secs(5));
    g.confidence_level(0.95);
    g.significance_level(0.05);
    g.noise_threshold(0.05);
}

/// xorshift64* PRNG — deterministic, no external dependencies. Used so the
/// committed dataset can be regenerated byte-for-byte (verify via re-hash).
fn next_u64(state: &mut u64) -> u64 {
    let mut x = *state;
    x ^= x << 13;
    x ^= x >> 7;
    x ^= x << 17;
    *state = x;
    x.wrapping_mul(0x2545_F491_4F6C_DD1D)
}

/// Generate `count` deterministic vectors of `dim` dimensions in `[0,1)`.
pub fn gen_f32(count: usize, dim: usize, seed: u64) -> Vec<Vec<f32>> {
    let mut state = seed;
    (0..count)
        .map(|_| {
            (0..dim)
                .map(|_| {
                    let bits = next_u64(&mut state);
                    // map u64 to [0,1) f32 using 21 bits of mantissa
                    ((bits >> 11) as f32) / ((1u64 << 21) as f32)
                })
                .collect()
        })
        .collect()
}

/// Serialize vectors as a little-endian f32 flat buffer.
pub fn write_dataset(path: &str, data: &[Vec<f32>]) {
    let first_len = data.first().map_or(0, |v| v.len());
    let mut buf = Vec::with_capacity(data.len() * first_len * 4);
    for v in data {
        for &x in v {
            buf.extend_from_slice(&x.to_le_bytes());
        }
    }
    std::fs::write(path, buf).expect("write synthetic dataset");
}

/// Read a dataset written by [`write_dataset`], reconstructing `DATASET_DIM`-wide vectors.
pub fn load_dataset(path: &str) -> Vec<Vec<f32>> {
    let bytes = std::fs::read(path).expect("read synthetic dataset");
    let floats: Vec<f32> = bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    floats.chunks(DATASET_DIM).map(|c| c.to_vec()).collect()
}

/// Return deterministic vectors of `count`×`dim`.
///
/// When `dim == DATASET_DIM` the committed file is loaded (first `count`
/// vectors); otherwise vectors are generated on the fly with [`DATASET_SEED`].
/// Either way the result is fully deterministic and reproducible.
pub fn synthetic_vectors(count: usize, dim: usize) -> Vec<Vec<f32>> {
    if dim == DATASET_DIM && Path::new(DATASET_PATH).exists() {
        let all = load_dataset(DATASET_PATH);
        if all.len() >= count {
            return all.into_iter().take(count).collect();
        }
    }
    gen_f32(count, dim, DATASET_SEED)
}
