/* auto-generated by NAPI-RS */
/* eslint-disable */
//
// Public TypeScript contract for vantadb-node.
//
// These declarations mirror the wire shapes the Rust side actually serializes:
//   - VantaValue tagged union      ← src/sdk/types.rs `enum VantaValue` (serde externally-tagged)
//   - MemoryRecord                 ← src/sdk/types.rs `VantaMemoryRecord` (node_id is a decimal
//                                    STRING: u128 exceeds Number.MAX_SAFE_INTEGER)
//   - GraphNodeRecord / edges      ← src/sdk/serialization/graph_types.rs (`VantaNodeRecord`,
//                                    `VantaEdgeRecord`; ids as decimal strings via u128_serde)
//   - SearchExplanation shapes     ← src/sdk/types.rs (`VantaSearchExplanation*`, fusion report)
//   - Capabilities                 ← built inline in src/lib.rs `capabilities()`
//
// Parameter overrides live on each `#[napi(ts_arg_type=…)]` in src/lib.rs per the
// official mechanism: https://napi.rs/docs/concepts/types-overwrite
// Runtime parsing/validation happens in Rust regardless of these types.

/** Tagged JSON representation of a graph/metadata field value (serde externally-tagged enum). */
export type VantaValue =
  | { String: string }
  | { Int: number }
  | { Float: number }
  | { Bool: boolean }
  /** RFC 3339 datetime string */
  | { DateTime: string }
  | { ListString: string[] }
  | { ListInt: number[] }
  | { ListFloat: number[] }
  | { ListBool: boolean[] }
  | { ListDateTime: string[] }
  | 'Null'

/** Metadata map attached to a memory record. */
export type VantaMetadata = Record<string, VantaValue>

/** Options for {@linkcode VantaDb.connect}. */
export interface ConnectOptions {
  read_only?: boolean
  memory_limit?: number
}

/** Input accepted by `put()` and `putBatch()`. */
export interface MemoryInput {
  namespace: string
  key: string
  payload: string
  metadata?: VantaMetadata
  vector?: number[]
  /** TTL in milliseconds relative to now. Must be a non-negative integer. */
  ttl_ms?: number
}

/** Persistent memory record returned by `put`/`putBatch`/`get`/`list`/`search`. */
export interface MemoryRecord {
  namespace: string
  key: string
  payload: string
  metadata: VantaMetadata
  created_at_ms: number
  updated_at_ms: number
  version: number
  /** Decimal string (u128 ids exceed Number.MAX_SAFE_INTEGER). */
  node_id: string
  vector: number[] | null
  /** Sparse term-weight vector keyed by dimension id. */
  sparse_vector?: Record<string, number> | null
  expires_at_ms: number | null
  superseded_by?: string | null
  superseded_at_ms?: number | null
}

/** Options for `list()`. */
export interface MemoryListOptions {
  filters?: VantaMetadata
  limit?: number
  cursor?: number
}

/** Result of `list()`. */
export interface MemoryListResult {
  records: MemoryRecord[]
  next_cursor?: number
}

/** Request accepted by `search()` and `explainSearch()`. */
export interface SearchRequest {
  namespace: string
  query_vector: number[]
  filters?: VantaMetadata
  text_query?: string
  top_k?: number
  distance_metric?: 'Cosine' | 'Euclidean'
  explain?: boolean
}

/** Per-term BM25 scoring decomposition. */
export interface Bm25TermContribution {
  token: string
  tf: number
  df: number
  doc_len: number
  contribution: number
}

/** Per-hit explanation with score, snippet, matched tokens, and BM25 breakdown. */
export interface SearchExplanationHit {
  /** Unique identity string (`namespace\0key`). */
  identity: string
  score: number
  snippet: string | null
  matched_tokens: string[]
  matched_phrases: string[]
  bm25_terms: Bm25TermContribution[]
  rrf_text_rank: number | null
  rrf_vector_rank: number | null
}

/** Counts and configuration for a hybrid (text+vector) fusion pass. */
export interface HybridFusionReport {
  text_candidates: number
  vector_candidates: number
  fused_candidates: number
  rrf_k: number
}

/** Explanation returned by `explainSearch()`. */
export interface SearchExplanation {
  route: string
  hits: SearchExplanationHit[]
  fusion_report: HybridFusionReport | null
}

/** Hit returned by `search()`. */
export interface MemorySearchHit {
  record: MemoryRecord
  /** Relevance score (BM25, cosine similarity, or RRF fused score). */
  score: number
  explanation?: SearchExplanationHit | null
}

/** Stable runtime capabilities returned by `capabilities()`. */
export interface Capabilities {
  runtime_profile: 'Enterprise' | 'Performance' | 'LowResource'
  persistence: boolean
  vector_search: boolean
  iql_queries: boolean
  read_only: boolean
}

/** Input accepted by `insertNode()`. */
export interface GraphNodeInput {
  /** Decimal string (safe above 2^53) or number. */
  id: string | number
  content?: string
  vector?: number[]
  /** Relational fields using the tagged `VantaValue` form. */
  fields?: Record<string, VantaValue>
}

/** Directed edge as returned inside {@linkcode GraphNodeRecord}. */
export interface GraphEdgeRecord {
  /** Decimal string node id this edge points to. */
  target: string
  label: string
  weight: number
  reverse: boolean
  created_at_ms: number
}

/** Graph node returned by `getNode()`. */
export interface GraphNodeRecord {
  /** Decimal string (u128 ids exceed Number.MAX_SAFE_INTEGER). */
  id: string
  fields: Record<string, VantaValue>
  vector: number[] | null
  vector_dimensions: number
  edges: GraphEdgeRecord[]
  confidence_score: number
  importance: number
  hits: number
  last_accessed: number
  epoch: number
  tier: 'Hot' | 'Cold'
  is_alive: boolean
}

/** Optional edge filtering for `graphFilteredTraversal()`. */
export interface GraphFilterOptions {
  labels?: number[]
  /** Inclusive `[from_ms, to_ms]` window on edge creation time. */
  time_range?: [number, number]
}

/** Degree-centrality entry returned by `graphDegree()`. */
export interface DegreeEntry {
  /** Decimal string node id. */
  id: string
  in_degree: number
  out_degree: number
}

/**
 * Report returned by `vacuum()`. The core SDK's `VacuumReport` does not
 * derive `Serialize`, so the binding builds the JSON object explicitly
 * (`MOD-10`, mirrors `src/storage/engine/mod.rs`).
 */
export interface VacuumReport {
  scanned_nodes: number
  removed_nodes: number
  reclaimed_bytes: number
  duration_ms: number
  success: boolean
}

/** Report returned by `rebuildIndex()`. */
export interface RebuildReport {
  scanned_nodes: number
  indexed_vectors: number
  skipped_tombstones: number
  duration_ms: number
  derived_rebuild_ms: number
  index_path: string
  success: boolean
}

/** Comparison operator for `FilterItem`. Mirrors `VantaFilterOp`. */
export type FilterOp = 'Eq' | 'Neq' | 'Gt' | 'Lt' | 'Gte' | 'Lte'

/** A single `{ field, op, value }` clause for `deleteByFilter` and `count`. */
export interface FilterItem {
  field: string
  op: FilterOp
  value: VantaValue
}

/** Explicit dense-vector index backend override for `searchWithMethod`. */
export type IndexMethod = 'Hnsw' | 'Ivf' | 'Flat' | 'DiskAnn' | 'Scann'
