/* auto-generated by NAPI-RS */
/* eslint-disable */
//
// Public TypeScript contract for vantadb-node.
//
// These declarations mirror the wire shapes the Rust side actually serializes:
//   - VantaValue tagged union      ← src/sdk/types.rs `enum VantaValue` (serde externally-tagged)
//   - MemoryRecord                 ← src/sdk/types.rs `VantaMemoryRecord` (node_id is a decimal
//                                    STRING: u128 exceeds Number.MAX_SAFE_INTEGER)
//   - GraphNodeRecord / edges      ← src/sdk/serialization/graph_types.rs (`VantaNodeRecord`,
//                                    `VantaEdgeRecord`; ids as decimal strings via u128_serde)
//   - SearchExplanation shapes     ← src/sdk/types.rs (`VantaSearchExplanation*`, fusion report)
//   - Capabilities                 ← built inline in src/lib.rs `capabilities()`
//
// Parameter overrides live on each `#[napi(ts_arg_type=…)]` in src/lib.rs per the
// official mechanism: https://napi.rs/docs/concepts/types-overwrite
// Runtime parsing/validation happens in Rust regardless of these types.

/** Tagged JSON representation of a graph/metadata field value (serde externally-tagged enum). */
export type VantaValue =
  | { String: string }
  | { Int: number }
  | { Float: number }
  | { Bool: boolean }
  /** RFC 3339 datetime string */
  | { DateTime: string }
  | { ListString: string[] }
  | { ListInt: number[] }
  | { ListFloat: number[] }
  | { ListBool: boolean[] }
  | { ListDateTime: string[] }
  | 'Null'

/** Metadata map attached to a memory record. */
export type VantaMetadata = Record<string, VantaValue>

/** Options for {@linkcode VantaDb.connect}. */
export interface ConnectOptions {
  read_only?: boolean
  memory_limit?: number
}

/** Input accepted by `put()` and `putBatch()`. */
export interface MemoryInput {
  namespace: string
  key: string
  payload: string
  metadata?: VantaMetadata
  vector?: number[]
  /** TTL in milliseconds relative to now. Must be a non-negative integer. */
  ttl_ms?: number
}

/** Persistent memory record returned by `put`/`putBatch`/`get`/`list`/`search`. */
export interface MemoryRecord {
  namespace: string
  key: string
  payload: string
  metadata: VantaMetadata
  created_at_ms: number
  updated_at_ms: number
  version: number
  /** Decimal string (u128 ids exceed Number.MAX_SAFE_INTEGER). */
  node_id: string
  vector: number[] | null
  /** Sparse term-weight vector keyed by dimension id. */
  sparse_vector?: Record<string, number> | null
  expires_at_ms: number | null
  superseded_by?: string | null
  superseded_at_ms?: number | null
}

/** Options for `list()`. */
export interface MemoryListOptions {
  filters?: VantaMetadata
  limit?: number
  cursor?: number
}

/** Result of `list()`. */
export interface MemoryListResult {
  records: MemoryRecord[]
  next_cursor?: number
}

/** Request accepted by `search()` and `explainSearch()`. */
export interface SearchRequest {
  namespace: string
  query_vector: number[]
  filters?: VantaMetadata
  text_query?: string
  top_k?: number
  distance_metric?: 'Cosine' | 'Euclidean'
  explain?: boolean
}

/** Per-term BM25 scoring decomposition. */
export interface Bm25TermContribution {
  token: string
  tf: number
  df: number
  doc_len: number
  contribution: number
}

/** Per-hit explanation with score, snippet, matched tokens, and BM25 breakdown. */
export interface SearchExplanationHit {
  /** Unique identity string (`namespace\0key`). */
  identity: string
  score: number
  snippet: string | null
  matched_tokens: string[]
  matched_phrases: string[]
  bm25_terms: Bm25TermContribution[]
  rrf_text_rank: number | null
  rrf_vector_rank: number | null
}

/** Counts and configuration for a hybrid (text+vector) fusion pass. */
export interface HybridFusionReport {
  text_candidates: number
  vector_candidates: number
  fused_candidates: number
  rrf_k: number
}

/** Explanation returned by `explainSearch()`. */
export interface SearchExplanation {
  route: string
  hits: SearchExplanationHit[]
  fusion_report: HybridFusionReport | null
}

/** Hit returned by `search()`. */
export interface MemorySearchHit {
  record: MemoryRecord
  /** Relevance score (BM25, cosine similarity, or RRF fused score). */
  score: number
  explanation?: SearchExplanationHit | null
}

/** Stable runtime capabilities returned by `capabilities()`. */
export interface Capabilities {
  runtime_profile: 'Enterprise' | 'Performance' | 'LowResource'
  persistence: boolean
  vector_search: boolean
  iql_queries: boolean
  read_only: boolean
}

/** Input accepted by `insertNode()`. */
export interface GraphNodeInput {
  /** Decimal string (safe above 2^53) or number. */
  id: string | number
  content?: string
  vector?: number[]
  /** Relational fields using the tagged `VantaValue` form. */
  fields?: Record<string, VantaValue>
}

/** Directed edge as returned inside {@linkcode GraphNodeRecord}. */
export interface GraphEdgeRecord {
  /** Decimal string node id this edge points to. */
  target: string
  label: string
  weight: number
  reverse: boolean
  created_at_ms: number
}

/** Graph node returned by `getNode()`. */
export interface GraphNodeRecord {
  /** Decimal string (u128 ids exceed Number.MAX_SAFE_INTEGER). */
  id: string
  fields: Record<string, VantaValue>
  vector: number[] | null
  vector_dimensions: number
  edges: GraphEdgeRecord[]
  confidence_score: number
  importance: number
  hits: number
  last_accessed: number
  epoch: number
  tier: 'Hot' | 'Cold'
  is_alive: boolean
}

/** Optional edge filtering for `graphFilteredTraversal()`. */
export interface GraphFilterOptions {
  labels?: number[]
  /** Inclusive `[from_ms, to_ms]` window on edge creation time. */
  time_range?: [number, number]
}

/** Degree-centrality entry returned by `graphDegree()`. */
export interface DegreeEntry {
  /** Decimal string node id. */
  id: string
  in_degree: number
  out_degree: number
}
/**
 * Native VantaDB handle exposed to Node.js. Thin wrapper over the SDK's
 * `VantaEmbedded`; all engine methods are async to avoid blocking the JS thread.
 */
export declare class VantaDb {
  /**
   * Open (or create) a VantaDB database at `path`.
   *
   * `path` may be a filesystem directory (persistent, fjall backend) or
   * `":memory:"` for a non-persistent in-memory database.
   *
   * `options` (optional): `{ read_only?: boolean, memory_limit?: number }`.
   */
  static connect(path: string, options?: ConnectOptions): Promise<VantaDb>
  /** Flush the WAL and memory-mapped files to disk. */
  flush(): Promise<void>
  /**
   * Close the database handle. Pending writes are flushed first.
   *
   * Once closing starts, new operations are rejected (`database is
   * closing`). This waits for every in-flight operation to finish before
   * flushing, so a fire-and-forget `put` whose `spawn_blocking` had not yet
   * run can never write after `close()` returns and be silently lost on
   * process exit.
   */
  close(): Promise<void>
  /**
   * Insert or update a persistent memory record.
   *
   * `record`: `{ namespace, key, payload, metadata?, vector?, ttl_ms? }`.
   * Returns the created/updated record with system timestamps and version.
   */
  put(record: MemoryInput): Promise<MemoryRecord>
  /** Insert or update multiple records. Returns the resulting records. */
  putBatch(records: MemoryInput[]): Promise<MemoryRecord[]>
  /** Retrieve a memory record by namespace and key. Returns `null` if absent. */
  get(namespace: string, key: string): Promise<MemoryRecord | null>
  /**
   * Delete a memory record by namespace and key. Returns `true` if a record
   * was actually deleted, `false` if it did not exist.
   */
  delete(namespace: string, key: string): Promise<boolean>
  /**
   * List records in a namespace with optional filters and cursor pagination.
   *
   * `options` (optional): `{ filters?: VantaMetadata, limit?: number, cursor?: number }`.
   * Returns `{ records: MemoryRecord[], next_cursor?: number }`.
   */
  list(namespace: string, options?: MemoryListOptions): Promise<MemoryListResult>
  /** Return all namespaces that contain at least one memory record. */
  listNamespaces(): Promise<Array<string>>
  /**
   * Search memory records by vector similarity (with optional filters and
   * text query). Returns hits ordered by relevance: each hit is
   * `{ record: MemoryRecord, score: number, explanation?: object }`.
   */
  search(request: SearchRequest): Promise<MemorySearchHit[]>
  /** Return stable runtime capabilities. */
  capabilities(): Capabilities
  /**
   * Insert or update a graph node directly.
   *
   * `input`: `{ id, content?, vector?, fields? }` — `id` is a decimal string
   * (or number; strings are the safe form for ids above 2^53), `fields` is an
   * object of tagged values (e.g. `{ "name": { "String": "Ada" } }`).
   */
  insertNode(input: GraphNodeInput): Promise<void>
  /** Retrieve a graph node by id. Returns `null` if absent. */
  getNode(id: string): Promise<GraphNodeRecord | null>
  /** Delete a graph node by id. The `reason` string is recorded for auditing. */
  deleteNode(id: string, reason: string): Promise<void>
  /**
   * Add a directed edge between two graph nodes.
   *
   * Automatically creates the reverse edge on the target node, enabling
   * bidirectional traversal queries. `weight` defaults to 1.0 and
   * `created_at_ms` to the current time.
   */
  addEdge(sourceId: string, targetId: string, label: string, weight?: number | undefined | null, createdAtMs?: number | undefined | null): Promise<void>
  /** Remove all edges between two nodes with the given label (both directions). */
  removeEdge(sourceId: string, targetId: string, label: string): Promise<void>
  /**
   * Breadth-first traversal from the given root node ids up to `max_depth`.
   *
   * `direction` is `"Forward"`, `"Reverse"`, or `"Both"`. Returns visited
   * node ids as decimal strings (u128 ids exceed JS safe integers).
   */
  graphBfs(roots: Array<string>, maxDepth: number, direction: string): Promise<Array<string>>
  /**
   * Depth-first traversal from the given root node ids up to `max_depth`.
   *
   * `direction` is `"Forward"`, `"Reverse"`, or `"Both"`. Returns visited
   * node ids as decimal strings.
   */
  graphDfs(roots: Array<string>, maxDepth: number, direction: string): Promise<Array<string>>
  /**
   * Topological sort of the subgraph reachable from the given root ids.
   *
   * Errors if the subgraph contains a cycle. Returns node ids as decimal strings.
   */
  graphTopologicalSort(roots: Array<string>): Promise<Array<string>>
  /** Return whether the subgraph reachable from the given roots forms a DAG. */
  graphIsDag(roots: Array<string>): Promise<boolean>
  /**
   * Breadth-first traversal with optional edge label/time filtering.
   *
   * `filter` is `{ labels?: number[], time_range?: [number, number] }` —
   * only edges whose label id is in `labels` (and, when given, created
   * inside the inclusive `time_range` window) are followed. `null`/`undefined`
   * disables both filters. Returns visited node ids as decimal strings.
   */
  graphFilteredTraversal(roots: Array<string>, maxDepth: number, direction: string, filter?: GraphFilterOptions): Promise<Array<string>>
  /**
   * Degree centrality (in/out counts) for the subgraph reachable from the roots.
   *
   * Returns an array of `{ id, in_degree, out_degree }` entries (u128 ids as
   * decimal strings).
   */
  graphDegree(roots: Array<string>): Promise<DegreeEntry[]>
  /**
   * Explain the search plan for a memory search request without executing it.
   *
   * Same request shape as `search()`. Returns
   * `{ route, hits, fusion_report }` with a per-hit scoring breakdown.
   */
  explainSearch(request: SearchRequest): Promise<SearchExplanation>
  // ── BND-10 parity additions ───────────────────────────────────────────────
  /** List every retained version of a memory record, ascending (v1..vN). */
  versions(namespace: string, key: string): Promise<MemoryRecord[]>
  /**
   * Retrieve a specific historical version of a memory record.
   * Returns `null` if the version does not exist.
   */
  getVersion(namespace: string, key: string, version: number): Promise<MemoryRecord | null>
  /**
   * Mark `oldKey` as superseded by `newKey` (ADR-028). Both keys must exist
   * and differ; `oldKey` must not already be superseded.
   */
  supersede(namespace: string, oldKey: string, newKey: string): Promise<void>
  /** Purge tombstoned nodes from the HNSW index. */
  vacuum(): Promise<VacuumReport>
  /** Rebuild the HNSW vector index, derived indexes, text index, and scalar index from scratch. */
  rebuildIndex(): Promise<RebuildReport>
  /**
   * Compact the vector store file (BFS grouping from the HNSW entry point).
   * Returns estimated bytes reclaimed.
   */
  compactLayout(): Promise<bigint>
  /** Compact the WAL: flush, archive the current WAL file, and start fresh.
   *  (contract alias: `compact_wal`)
   */
  compactWal(): Promise<void>
  /**
   * Scan every memory record and physically delete those whose TTL has expired.
   * Returns the number of records purged.
   * (contract alias: `purge_expired`)
   */
  purgeExpired(): Promise<bigint>
  /**
   * Delete every record in `namespace` whose metadata matches the filter.
   * The filter must contain at least one item.
   */
  deleteByFilter(namespace: string, filter: Array<FilterItem>): Promise<bigint>
  /** Count records in a namespace, optionally filtered. Pass `null` for no filter. */
  count(namespace: string, filter: Array<FilterItem> | null | undefined): Promise<bigint>
  /** Find records similar to the vector of an existing record (filters out the source). */
  similarToKey(namespace: string, key: string, topK: number): Promise<MemorySearchHit[]>
  /**
   * Same as `search()` with an explicit dense-vector index backend override.
   * `method` accepts `'Hnsw' | 'Ivf' | 'Flat' | 'DiskAnn' | 'Scann'`, or
   * `null`/`undefined` for automatic routing.
   */
  searchWithMethod(request: SearchRequest, method: IndexMethod | null | undefined): Promise<MemorySearchHit[]>
  /**
   * Search across multiple namespaces in a single call. The `namespace`
   * field on `request` is ignored; results are merged by descending score.
   */
  searchMulti(namespaces: Array<string>, request: SearchRequest): Promise<MemorySearchHit[]>
}
export type VantaDB = VantaDb
