name: cargo-deny
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: EmbarkStudios/cargo-deny-action@8f84122a46a358a27cb0625d85ad60ab436a1b87
        with:
          command: check advisories licenses bans sources